version: '3.8'

services:
  yii2-app:
    image: your-dockerhub-username/yii2-app:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

